CREATE TABLE streetmarket(
	id SERIAL,
	longitude varchar(10),
	latitude varchar(10),
	set_census varchar(15),
	area_deliberation varchar(13),
	cod_district varchar(9),
	district varchar(18),
	cod_sub_city_hall varchar(2),
	sub_city_hall varchar(25),
	region_5 varchar(6),
	region_8 varchar(7),
	name_sm varchar(30),
	registration varchar(6),
	address varchar(34),
	number_address varchar(15),
	neighbourhood varchar(20),
	reference varchar(50),
)
